services:
  - type: web
    name: web-clipboard
    runtime: docker
    env: docker
    build:
      dockerfile: Dockerfile
    envVars:
      - key: SPRING_PROFILES_ACTIVE
        value: production
    resources:
      memoryMB: 512
      cpu: 0.25
    disk:
      name: h2_data
      mountPath: /data
      sizeGB: 1  # Small size since H2 is lightweight

databases:
  - name: clipboarddb
    plan: free